version: '3'

services:
  serial-server:
    network_mode: host
    image: graymatics1/serial-back-end:1.0.2
    restart: always
    volumes:
      - /home/alex/Desktop/office/system/.scrt.env:/usr/src/app/.scrt.env

  serial-ui:
    image: graymatics1/serial-front-end:1.0.4
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/alex/Desktop/office/system/nginx.conf:/etc/nginx/conf.d/default.conf